export {default as DetailsScreen} from "./DetailsScreen"
export {default as HomeScreen} from "./HomeScreen"
export {default as LoginScreen} from "./LoginScreen"
export {default as RegisterScreen} from "./RegisterScreen"
export {default as TeamScreen} from "./TeamScreen"
export {default as SettingsScreen} from "./SettingsScreen"